export const movies = [
  {
    id: "1",
    title: "Inception",
    comments: 0,
    rating: 4.7,
    description: "A mind-bending thriller by Christopher Nolan.",
    isFeatured: true,
    commentsList: [],
  },
  {
    id: "2",
    title: "Interstellar",
    comments: 2,
    rating: 4.8,
    description: "A space exploration film by Christopher Nolan.",
    isFeatured: false,
    commentsList: [
      "Visually stunning and emotional.",
      "Hans Zimmer's score was unforgettable.",
    ],
  },
  {
    id: "3",
    title: "The Dark Knight",
    comments: 3,
    rating: 4.9,
    description: "The iconic Batman film directed by Christopher Nolan.",
    isFeatured: true,
    commentsList: [
      "Heath Ledger was phenomenal.",
      "Best superhero movie ever.",
      "Dark, deep, and unforgettable.",
    ],
  },
  {
    id: "4",
    title: "Titanic",
    comments: 3,
    rating: 4.9,
    description: "A love story that unfolds the ill-fated romance aboard the Titanic.",
    commentsList: [
      "A timeless classic.",
      "Beautifully tragic.",
      "L.D. and Kate are perfect together.",
    ],
    isFeatured: false,
  },
  {
    id: "5",
    title: "The Matrix",
    comments: 2,
    rating: 4.8,
    description: "A hacker discovers the reality he lives in is a simulation.",
    isFeatured: true,
    commentsList: [
      "Changed sci-fi forever.",
      "Red pill or blue pill? Iconic.",
    ],
  },
  {
    id: "6",
    title: "The Shawshank Redemption",
    comments: 2,
    rating: 5.0,
    description: "Hope and friendship blossom in a prison.",
    isFeatured: true,
    commentsList: [
      "Emotional and powerful.",
      "A masterpiece from start to end.",
    ],
  },
  {
    id: "7",
    title: "Pulp Fiction",
    comments: 3,
    rating: 4.6,
    description: "Tarantino’s cult classic with intertwined crime stories.",
    isFeatured: false,
    commentsList: [
      "Dialogue is top-tier.",
      "Unforgettable characters.",
      "Unique storytelling structure.",
    ],
  },
  {
    id: "8",
    title: "Avengers: Endgame",
    comments: 3,
    rating: 4.5,
    description: "The epic conclusion of Marvel’s Infinity Saga.",
    isFeatured: true,
    commentsList: [
      "I cried at least twice.",
      "So satisfying as a Marvel fan.",
      "Tony Stark's ending was perfect.",
    ],
  },
  {
    id: "9",
    title: "Gladiator",
    comments: 1,
    rating: 4.7,
    description: "A betrayed Roman general seeks vengeance as a gladiator.",
    isFeatured: false,
    commentsList: [
      "Russell Crowe's best role.",
    ],
  },
  {
    id: "10",
    title: "The Godfather",
    comments: 3,
    rating: 5.0,
    description: "The rise of the Corleone crime family.",
    isFeatured: true,
    commentsList: [
      "Legendary filmmaking.",
      "The definition of a classic.",
      "Cinematic perfection.",
    ],
  },
  {
    id: "11",
    title: "The Wolf of Wall Street",
    comments: 2,
    rating: 4.4,
    description: "A true story of greed and excess in the stock market.",
    isFeatured: false,
    commentsList: [
      "Leo was robbed at the Oscars.",
      "Fast-paced and hilarious.",
    ],
  },
  {
    id: "12",
    title: "Fight Club",
    comments: 2,
    rating: 4.9,
    description: "An underground fight club leads to chaos.",
    isFeatured: true,
    commentsList: [
      "The twist blew my mind.",
      "Stylish and thought-provoking.",
    ],
  },
  {
    id: "13",
    title: "Forrest Gump",
    comments: 1,
    rating: 4.8,
    description: "A man's life journey through history and love.",
    isFeatured: false,
    commentsList: [
      "Life really is like a box of chocolates.",
    ],
  },
  {
    id: "14",
    title: "La La Land",
    comments: 2,
    rating: 4.3,
    description: "A jazz musician and an actress fall in love in LA.",
    isFeatured: false,
    commentsList: [
      "Bittersweet and beautiful.",
      "That ending though... wow.",
    ],
  },
  {
    id: "15",
    title: "Joker",
    comments: 2,
    rating: 4.6,
    description: "The origin story of Gotham’s infamous villain.",
    isFeatured: true,
    commentsList: [
      "Disturbing and brilliant.",
      "Joaquin Phoenix is a beast.",
    ],
  },
    {
    id: "16",
    title: "Whiplash",
    comments: 2,
    rating: 4.7,
    description: "A young drummer pushed to greatness by an intense mentor.",
    isFeatured: true,
    commentsList: [
      "Intense and brilliant performances.",
      "Are you rushing or dragging?!",
    ],
  },
  {
    id: "17",
    title: "Parasite",
    comments: 3,
    rating: 4.9,
    description: "A poor family infiltrates a rich household in this Korean thriller.",
    isFeatured: false,
    commentsList: [
      "Masterpiece of storytelling.",
      "Deserved the Oscar!",
      "Social commentary done right.",
    ],
  },
  {
    id: "18",
    title: "The Social Network",
    comments: 2,
    rating: 4.5,
    description: "The rise of Facebook and the drama behind it.",
    isFeatured: false,
    commentsList: [
      "Aaron Sorkin's script is gold.",
      "Jesse Eisenberg nailed it.",
    ],
  },
  {
    id: "19",
    title: "Dune (2021)",
    comments: 2,
    rating: 4.4,
    description: "A noble family becomes embroiled in a war for control of a desert planet.",
    isFeatured: true,
    commentsList: [
      "Incredible visuals and sound.",
      "Can’t wait for Part 2!",
    ],
  },
  {
    id: "20",
    title: "Oppenheimer",
    comments: 2,
    rating: 4.8,
    description: "The story of the father of the atomic bomb.",
    isFeatured: true,
    commentsList: [
      "Heavy and thought-provoking.",
      "Cillian Murphy was exceptional.",
    ],
  },
  {
    id: "21",
    title: "Barbie",
    comments: 3,
    rating: 4.2,
    description: "A colorful, clever take on the iconic doll’s identity.",
    isFeatured: false,
    commentsList: [
      "Funny and surprisingly deep.",
      "Great message for all ages.",
      "Ryan Gosling as Ken? Hilarious!",
    ],
  },
  {
    id: "22",
    title: "Everything Everywhere All At Once",
    comments: 3,
    rating: 4.6,
    description: "An absurd yet emotional multiverse adventure.",
    isFeatured: true,
    commentsList: [
      "Absolutely wild ride!",
      "Michelle Yeoh is a queen.",
      "So weird but so good.",
    ],
  },
  {
    id: "23",
    title: "Black Panther",
    comments: 2,
    rating: 4.5,
    description: "The king of Wakanda fights for his throne and people.",
    isFeatured: false,
    commentsList: [
      "Wakanda Forever!",
      "Emotional tribute to Chadwick.",
    ],
  },
  {
    id: "24",
    title: "Spider-Man: No Way Home",
    comments: 3,
    rating: 4.7,
    description: "Multiverse chaos and redemption for Peter Parker.",
    isFeatured: true,
    commentsList: [
      "Nostalgia overload!",
      "All three Spideys together!",
      "Crowd went wild in theaters.",
    ],
  },
  {
    id: "25",
    title: "The Prestige",
    comments: 2,
    rating: 4.8,
    description: "Two rival magicians go to dangerous lengths.",
    isFeatured: false,
    commentsList: [
      "Twist after twist!",
      "Loved the mystery and tension.",
    ],
  },
  {
    id: "26",
    title: "Shutter Island",
    comments: 2,
    rating: 4.6,
    description: "A U.S. Marshal investigates a psychiatric facility.",
    isFeatured: false,
    commentsList: [
      "Haunting and gripping.",
      "That ending still haunts me.",
    ],
  },
  {
    id: "27",
    title: "The Grand Budapest Hotel",
    comments: 2,
    rating: 4.3,
    description: "A whimsical tale of a hotel concierge and his adventures.",
    isFeatured: true,
    commentsList: [
      "Wes Anderson’s style is unmatched.",
      "Charming and hilarious.",
    ],
  },
  {
    id: "28",
    title: "Mad Max: Fury Road",
    comments: 3,
    rating: 4.5,
    description: "A high-octane escape across a dystopian wasteland.",
    isFeatured: false,
    commentsList: [
      "Non-stop action!",
      "Visually stunning.",
      "Furiosa is iconic.",
    ],
  },
  {
    id: "29",
    title: "Coco",
    comments: 2,
    rating: 4.9,
    description: "A boy journeys through the Land of the Dead to understand his family.",
    isFeatured: false,
    commentsList: [
      "I cried at the ending.",
      "Heartwarming and beautiful.",
    ],
  },
  {
    id: "30",
    title: "Soul",
    comments: 2,
    rating: 4.7,
    description: "A musician finds meaning beyond life and jazz.",
    isFeatured: false,
    commentsList: [
      "Makes you think about life.",
      "Pixar did it again!",
    ],
  },
];
